### ISSUE TITLE
Mention to disable QtCreator 4.7 new clang based code model

### ISSUE THREAD

**Issue by kelteseth** [NAlphaDev/Unreal-Qt-project-generator#6]
Hi,

The new replacement for the QtCreator code model/autocompletion is with the size of the Unreal Engine way to slow. Luckily the old code model is still available simply by disabling the clang code model via:

QtCreator  -> Help -> About Plugins -> c++ -> ClangCodeModel *//Disable the plugin and restart QtCreator

I think we should mention this somewhere in the readme :)

This is similar to this project/issue https://github.com/xBazilio/UE4_Win_QtCreatorSourceCodeAccess/issues/6

**Comment by kelteseth** [comment]
Thanks for the fast response :)

**Comment by nibau** [comment]
Hi, you're welcome ;)
I have added the information to the readme as well as to the tutorial in the forum post.

Even tough clang code model is great for normal C++ development, I agree that in most cases you are better off with the built-in code model for UE development at the moment. 
Clang code model performance will hopefully continue to improve over time so this recommendation might change with future QtCreator versions.
